In [1]:
import numpy as np

In [2]:
ytrue=np.array([0.70,0,1,0.30,0.5])
ypred=np.array([1,0,0,1,1])

In [3]:
def mean_absolute_error(ytrue,ypred):
  err=0
  for yt,yp in zip(ytrue,ypred):
    err+=abs(yt-yp)
  print("total error",err)
  mae=err/len(ytrue)
  return mae

me=mean_absolute_error(ytrue,ypred)
print('Mean absolute error is',me)

total error 2.5
Mean absolute error is 0.5


In [4]:
def mean_root_square_error(ytrue,ypred):
  err=0
  for yt,yp in zip(ytrue,ypred):
    err+=(yt-yp)**2
  print("square error:",err)
  mrse=(err/len(ytrue))**(1/2)
  return mrse



ms=mean_root_square_error(ytrue,ypred)

print('Mean root square error is',ms)

square error: 1.83
Mean root square error is 0.6049793384901669


In [5]:
np.log(1)

0.0

In [6]:
ep=1e-15

In [7]:
ypred

array([1, 0, 0, 1, 1])

In [8]:
ypred_new=[max(i,ep) for i in ypred]
ypred_new

[1, 1e-15, 1e-15, 1, 1]

In [9]:
ypred_new=[min(i,1-ep) for i in ypred_new]
ypred_new

[0.999999999999999, 1e-15, 1e-15, 0.999999999999999, 0.999999999999999]

In [10]:
ypred_new=np.array(ypred_new)
ypred_new

array([1.e+00, 1.e-15, 1.e-15, 1.e+00, 1.e+00])

In [11]:
np.log(ypred_new)

array([-9.99200722e-16, -3.45387764e+01, -3.45387764e+01, -9.99200722e-16,
       -9.99200722e-16])

In [12]:
-np.mean(ytrue*np.log(ypred_new)+(1-ytrue)*(1-np.log(ypred_new)))

-0.49999999999999944

In [13]:
def log_loss(ytrue,ypred):
  ep=1e-15
  ypred_new=[max(i,ep) for i in ypred]
  ypred_new=[min(i,1-ep) for i in ypred_new]
  ypred_new=np.array(ypred_new)
  return -np.mean(ytrue*np.log(ypred_new)+(1-ytrue)*(1-np.log(ypred_new)))

In [14]:
log_loss(ytrue,ypred)

-0.49999999999999944

#assignment 2
1.impliment mean square error using numpy

2.without using numpy

In [15]:
def mean_square_error(ytrue,ypred):
  err=0
  for yt,yp in zip(ytrue,ypred):
    err+=np.square(yt-yp)
  print("square error:",err)
  mse=err/len(ytrue)
  return mse

ms=mean_square_error(ytrue,ypred)
print('Mean square error is',ms)

square error: 1.83
Mean square error is 0.366


In [16]:
def mean_square_error(ytrue,ypred):
  err=0
  for yt,yp in zip(ytrue,ypred):
    err+=(yt-yp)**2
  print("square error:",err)
  mse=err/len(ytrue)
  return mse

ms=mean_square_error(ytrue,ypred)
print('Mean square error is',ms)

square error: 1.83
Mean square error is 0.366
