In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_wine

In [2]:
dataset=load_wine()

In [3]:
df=pd.DataFrame(dataset['data'],columns=dataset['feature_names'])

In [4]:
df.head()

alcohol  malic_acid   ash  ...   hue  od280/od315_of_diluted_wines  proline
0    14.23        1.71  2.43  ...  1.04                          3.92   1065.0
1    13.20        1.78  2.14  ...  1.05                          3.40   1050.0
2    13.16        2.36  2.67  ...  1.03                          3.17   1185.0
3    14.37        1.95  2.50  ...  0.86                          3.45   1480.0
4    13.24        2.59  2.87  ...  1.04                          2.93    735.0

[5 rows x 13 columns]

In [5]:
df['quality']=dataset['target']
df.head()

alcohol  malic_acid   ash  ...  od280/od315_of_diluted_wines  proline  quality
0    14.23        1.71  2.43  ...                          3.92   1065.0        0
1    13.20        1.78  2.14  ...                          3.40   1050.0        0
2    13.16        2.36  2.67  ...                          3.17   1185.0        0
3    14.37        1.95  2.50  ...                          3.45   1480.0        0
4    13.24        2.59  2.87  ...                          2.93    735.0        0

[5 rows x 14 columns]

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 14 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   alcohol                       178 non-null    float64
 1   malic_acid                    178 non-null    float64
 2   ash                           178 non-null    float64
 3   alcalinity_of_ash             178 non-null    float64
 4   magnesium                     178 non-null    float64
 5   total_phenols                 178 non-null    float64
 6   flavanoids                    178 non-null    float64
 7   nonflavanoid_phenols          178 non-null    float64
 8   proanthocyanins               178 non-null    float64
 9   color_intensity               178 non-null    float64
 10  hue                           178 non-null    float64
 11  od280/od315_of_diluted_wines  178 non-null    float64
 12  proline                       178 non-null    float64
 13  quali

In [26]:
df.quality.unique()

array([0, 1, 2])

In [7]:
from sklearn.model_selection import train_test_split
X=df.iloc[:,0:13]
Y=df.iloc[:,-1]
xtrain,xtest,ytrain,ytest = train_test_split(X,Y,test_size=0.30,random_state=1)

In [8]:
print(f'xtrain shape {xtrain.shape}')
print(f'xtest shape {xtest.shape}')
print(f'ytrain shape {ytrain.shape}')
print(f'ytest shape {ytest.shape}')

xtrain shape (124, 13)
xtest shape (54, 13)
ytrain shape (124,)
ytest shape (54,)


In [9]:
from sklearn.preprocessing import MinMaxScaler

In [10]:
scaler =MinMaxScaler()
xtrain_transform=scaler.fit_transform(xtrain)
xtest_transform=scaler.fit_transform(xtest)
xtrain_transform[:10]

array([[0.27631579, 0.18979592, 0.40522876, 0.42196532, 0.11956522,
        0.2137931 , 0.24472574, 0.78      , 0.38801262, 0.09556314,
        0.45217391, 0.36630037, 0.16396104],
       [0.37894737, 0.12653061, 0.32679739, 0.45086705, 1.        ,
        0.52413793, 0.407173  , 0.38      , 0.90536278, 0.11262799,
        0.52173913, 0.4981685 , 0.5349026 ],
       [0.74736842, 0.20408163, 0.71895425, 0.47398844, 0.40217391,
        0.67931034, 0.55485232, 0.48      , 0.42586751, 0.27474403,
        0.6       , 0.78021978, 0.51704545],
       [0.22105263, 0.69591837, 0.45098039, 0.56647399, 0.13043478,
        0.64827586, 0.56751055, 0.16      , 0.78864353, 0.12969283,
        0.16521739, 0.86813187, 0.08279221],
       [0.41315789, 0.31836735, 0.32679739, 0.42196532, 0.26086957,
        0.22068966, 0.06751055, 1.        , 0.16719243, 0.49658703,
        0.14782609, 0.11355311, 0.33847403],
       [0.54736842, 0.02244898, 0.        , 0.21965318, 0.08695652,
        0.68965517, 0.59915

In [11]:
from sklearn.neural_network import MLPClassifier

In [12]:
model=MLPClassifier(hidden_layer_sizes= (150,100,45), activation='relu',max_iter=300,solver='adam')

In [13]:
model.fit(xtrain_transform,ytrain)

MLPClassifier(hidden_layer_sizes=(150, 100, 45), max_iter=300)

In [14]:
ypred=model.predict(xtest_transform)

In [15]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [16]:
acc= accuracy_score(ytest,ypred)
print('accuracy =',acc)

accuracy = 1.0


In [17]:
cm=confusion_matrix(ytest,ypred)
print(cm)

[[23  0  0]
 [ 0 19  0]
 [ 0  0 12]]


In [18]:
from sklearn.metrics import classification_report
cr=classification_report(ytest,ypred)
print(cr)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        23
           1       1.00      1.00      1.00        19
           2       1.00      1.00      1.00        12

    accuracy                           1.00        54
   macro avg       1.00      1.00      1.00        54
weighted avg       1.00      1.00      1.00        54



In [19]:
m=[100,200,250,300,500]
s=['sgd','adam']
a1=['tanh','logistic','relu']
a2=[0.0001,0.05,0.10]

In [20]:
from sklearn.model_selection import GridSearchCV
param_grid = {'max_iter':m, 'solver':s, 'activation':a1,'alpha': a2}

In [21]:
gridsearch = GridSearchCV(model, param_grid,cv=5)

In [22]:
gridsearch.fit(xtrain,ytrain)

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multi

GridSearchCV(cv=5,
             estimator=MLPClassifier(hidden_layer_sizes=(150, 100, 45),
                                     max_iter=300),
             param_grid={'activation': ['tanh', 'logistic', 'relu'],
                         'alpha': [0.0001, 0.05, 0.1],
                         'max_iter': [100, 200, 250, 300, 500],
                         'solver': ['sgd', 'adam']})

In [23]:
gridsearch.best_params_

{'activation': 'logistic', 'alpha': 0.05, 'max_iter': 500, 'solver': 'adam'}

In [24]:
gridsearch.best_score_

0.9596666666666666